version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build: .
    command: uvicorn backend.asgi:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/postgres
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend
    command: npm run dev --workspace frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  db-data:
